# Generated by Django 6.0.1 on 2026-01-13 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_uid', models.CharField(max_length=50, unique=True)),
                ('api_key', models.CharField(max_length=64, unique=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='houses.house')),
            ],
        ),
    ]
