# Generated by Django 5.2.8 on 2026-01-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_device_is_active_alter_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
