# Generated by Django 5.2.8 on 2026-01-23 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device_device_name_device_device_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='device_name',
        ),
        migrations.RemoveField(
            model_name='device',
            name='device_type',
        ),
    ]
