# Generated by Django 5.2.8 on 2026-01-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power_events', '0002_alter_powerevent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerevent',
            name='power',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
